version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: schchngr-sdocs_server_1
      APP_PORT: 11000

  server:
    image: ghcr.io/schaechinger/docs:latest@sha256:8ab602143c9e8e1904f045f77826ea5e5dca6b7a90180e8c84de2e1e4322568c
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/config:/usr/src/app/config
      - ${APP_DATA_DIR}/data/data:/usr/src/app/data
      - ${APP_DATA_DIR}/data/fonts:/usr/src/app/fonts
