version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: schchngr-sdocs_server_1
      APP_PORT: 11000

  server:
    image: ghcr.io/schaechinger/docs:latest@sha256:063cca9ba584ade96ef4b4900ec153e87b42adc1c276d20e293766e41bf19336
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/config:/usr/src/app/config
      - ${APP_DATA_DIR}/data/data:/usr/src/app/data
      - ${APP_DATA_DIR}/data/fonts:/usr/src/app/fonts
