version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: schchngr-sdocs_server_1
      APP_PORT: 11000

  server:
    image: ghcr.io/schaechinger/docs:latest@sha256:545f794f7cb7c307256706a3972eec6a4643b58d6f99804fbc7d5da841443d0c
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/config:/usr/src/app/config
      - ${APP_DATA_DIR}/data/data:/usr/src/app/data
      - ${APP_DATA_DIR}/data/fonts:/usr/src/app/fonts
